export const allDances = [
    'African dance',
    'All Dance Styles',
    'Afro House',
    'Bachata',
    'Ballroom',
    'Balboa',
    'Shag',
    'Balkan Disco',
    'Ballett',
    'Blues',
    'Bellydance',
    'Bolero',
    'Bollywood',
    'Boogie Woogie',
    'Bossa Nova',
    'Bourlesque',
    'Zouk',
    'Breakdance',
    'Burlesque',
    'ChaChaCha',
    'Changa',
    'Charleston',
    'Cheloveki',
    'Contemporary',
    'Contact',
    'Country Dance',
    'Cumbia',
    'Pogo',
    'Poledance',
    'Dancehall',
    'Dirty Dancing',
    'Disco',
    'Discofox',
    'Ecstatic',
    'Ententanz',
    'Flamenco',
    'Folk',
    'Forró',
    'Fox',
    'Funk',
    'Guaracha',
    'Go Go Dance',
    'Happy Feet',
    'Hawaiian',
    'Hula',
    'Hip Hop',
    'Hoop Dance',
    'House',
    'Igbo',
    'Indian',
    'Indie',
    'Inner Dance',
    'Irish Dance',
    'Jaw',
    'Jazz Dance',
    'Jive',
    'Kizomba',
    'Lambada',
    'Lindy Hop',
    'Linedance',
    'Line Dance',
    'Mambo',
    'Merengue',
    'No Dance Provided',
    'Omambo',
    'Oriental Dance',
    'Q dance',
    'ROCK\'N\'ROLL',
    'Rave',
    'Reggae',
    'Reggaeton',
    'Rock N Roll',
    'Rock Step',
    'Rueda',
    'Rumba',
    'Salsa',
    'Samba',
    'Sambo',
    'Semba',
    'Son',
    'Shim Sham',
    'Show Dance',
    'Shuffle',
    'Square',
    'Streetdance',
    'Sway',
    'Swing',
    'Table Dance',
    'Tango',
    'Tap Dance',
    'Techno',
    'Timba',
    'Trance',
    'Twerk',
    'Twist',
    'Urban Kiz',
    'Quickstep',
    'Waltz',
    'Wiener Walzer',
    'Western',
    'Workshop Latino',
    'Yogadance',
    'Zumba',
  ]